### ISSUE TITLE
Could not use it like a component 

### ISSUE THREAD

**Issue by lunguyen1986** [rafaelklaessen/react-tradingview-widget#13]
I try your example and it alway said that " Invariant Violation: View config not found for name article"
I posted my code bellow 
[import React, { Component } from 'react';
import {
    Text, View, Image, TouchableHighlight,StyleSheet,Dimensions, TouchableOpacity
} from 'react-native'; 

import TradingViewWidget, { Themes } from 'react-tradingview-widget';

class TradingView extends Component{
    render(){
        return(<TradingViewWidget
            symbol="NASDAQ:AAPL"
            theme={Themes.DARK}
            locale="fr"
            autosize
          />)
    }
}
export default TradingViewWidget

**Comment by rafaelklaessen** [comment]
This component does not work on react-native (and never will because TradingView itself only supports web)
