### ISSUE TITLE
no side bar with drawing tools rendering

### ISSUE THREAD

**Issue by Onesun15** [rafaelklaessen/react-tradingview-widget#14]
Can't see the drawing tools when I have hide_side_toolbar=true.

**Comment by rafaelklaessen** [comment]
Try
```javascript
<TradingViewWidget symbol="NASDAQ:AAPL" hide_side_toolbar={false} />
```
when you want to show it and try
```javascript
<TradingViewWidget symbol="NASDAQ:AAPL" hide_side_toolbar />
```
when you want to hide it.

**Comment by Onesun15** [comment]
Yes I tried this.  I didn't work on my end.  Any other suggestions?

**Comment by rafaelklaessen** [comment]
For me it does work:
![screen shot 2018-05-18 at 19 39 27](https://user-images.githubusercontent.com/15846964/40249415-3481484e-5ad3-11e8-9fa5-d875b2a18a71.png)

With the following code:
```javascript
import React from 'react';
import './App.css';
import TradingViewWidget, { Themes } from 'react-tradingview-widget';

const App = () => (
  <TradingViewWidget symbol="NASDAQ:AAPL" autosize hide_side_toolbar={false} />
);

export default App;
```

**Comment by BeomyeonAndrewKim** [comment]
I think height size affect side tool bar maybe at least 453px above.

**Comment by rafaelklaessen** [comment]
Hmmm could be. I'm closing this issue then since it's not a problem with this component.
