### ISSUE TITLE
Datafeed

### ISSUE THREAD

**Issue by phucsang0spt** [rafaelklaessen/react-tradingview-widget#15]
How I set datafeet ?

**Comment by rafaelklaessen** [comment]
You'll have to use the TradingView datafeed by setting the symbol. In my example I used NASDAQ:AAPL which will give you the datafeed of Apple Inc.'s stock price.
If you want to use, for example, Bitcoin, use BINANCE:BTCUSD.

**Comment by germanst** [comment]
I have the same doubt, what about if I need to use my own feed?

**Comment by rafaelklaessen** [comment]
Can you use your own datafeed with the [TradingView Advanced Real-Time Chart Widget](https://www.tradingview.com/widget/advanced-chart/)?

**Comment by poormohammadi** [comment]
That means you are not supposed to support datafeed in your library , yes?
So this library is not useful for this purpose.

**Comment by rafaelklaessen** [comment]
I suppose so yes. The thing is, if TradingView's widget supports it, this component supports it. I just can't find any docs for datafeeds with TradingView's widget, hence my question.
