### ISSUE TITLE
datafeed

### ISSUE THREAD

**Issue by poormohammadi** [rafaelklaessen/react-tradingview-widget#16]
how to change datafeed in this library?
connecting to a custom server required. 
now , 

```
<TradingViewWidget
          locale="fa_IR"
          symbol="BTCUSD"
          theme={Themes.DARK}
          datafeed={new Datafeeds.UDFCompatibleDatafeed("https://demo_feed.tradingview.com")}

        />
```
does not work. how to import Datafeeds or any solution to run trading view chart library with custom data fetching from ws protocol.

**Comment by rafaelklaessen** [comment]
This issue was already created and therefore I'm marking this one as a duplicate.

Please answer my question in #15
