### ISSUE TITLE
[Suggestion/Question] Custom timeseries

### ISSUE THREAD

**Issue by Partysun** [rafaelklaessen/react-tradingview-widget#19]
Hello, great job 👍 

Can we render any custom timeseries in this widget?
I want to show the asset chart and my data in the additional layer.

Thank you

**Comment by rafaelklaessen** [comment]
Can you do this with the [Advanced Real-Time Chart Widget](https://www.tradingview.com/widget/advanced-chart/)?

If not, you can't do it with this package either, I'm sorry :(
