### ISSUE TITLE
full screen on load

### ISSUE THREAD

**Issue by amlcodes** [rafaelklaessen/react-tradingview-widget#24]
full screen on load

**Comment by AurelReb** [comment]
I found a fix.
You can use it by importing my fork of this library:
- `npm install AurelDev/react-tradingview-widget --save`
or
- `yarn add AurelDev/react-tradingview-widget`

**Comment by rafaelklaessen** [comment]
Hi, could you be a bit more specific? I've no clue what you mean.

@AurelReb if you'd like to, perhaps you could create a PR and then I can merge your fix into this repo?

**Comment by AurelReb** [comment]
Actually it is a rare bug which appears when the TradingViewWidget component is unmounted before the chart is rendered. Therefore the chart is rendered after in full screen in the `body` element.
I'll create a PR with my fix soon

**Comment by rafaelklaessen** [comment]
Merged, thanks!
