### ISSUE TITLE
pass toolbar_bg with #ff0000 format not work

### ISSUE THREAD

**Issue by gasolin** [rafaelklaessen/react-tradingview-widget#26]
found pass `toolbar_bg` color with `#ff0000` format not work, 
but doing `toolbar_bg='red'` does change the color

It might not related to this component, but directly related to the widget itself...

**Comment by rafaelklaessen** [comment]
Thanks for the issue!

Since this component simply passes all props on to the TradingView widget itself, I suppose this is indeed an issue with the underlying widget, like you suggested.
