### ISSUE TITLE
Price not shown when autosize or custom size

### ISSUE THREAD

**Issue by matthlavacka** [rafaelklaessen/react-tradingview-widget#30]
When I use autosize or custom size the half width of the price right bar is not visible.

<img width="466" alt="Screenshot 2019-07-25 at 23 09 27" src="https://user-images.githubusercontent.com/8323766/61909100-9041cb00-af31-11e9-90d9-6366e830f890.png">

**Comment by matthlavacka** [comment]
Actually the same issue happens in normal view, without custom or autosize.

**Comment by rafaelklaessen** [comment]
I'm afraid that's an issue with TradingView itself then. This component is only a very simple wrapper.

**Comment by matthlavacka** [comment]
You're right, closing this. Thanks for the prompt reply!
