### ISSUE TITLE
Drawing tools sidebar won't render

### ISSUE THREAD

**Issue by jHwls** [rafaelklaessen/react-tradingview-widget#45]
Hi there 👋 

Unable to get the drawing tools to render with the latest (1.3.2) release--pretty sure this was working before. Here's a sandbox with the `hideSideToolbar` prop set to false. Is there another prop I'm missing? Thanks

https://codesandbox.io/s/goofy-http-3bg9j?file=/src/App.js:312-327

**Comment by KavehMina** [comment]
hide_side_toolbar={false}
