### ISSUE TITLE
Whether I can access my own data

### ISSUE THREAD

**Issue by jiameng123** [rafaelklaessen/react-tradingview-widget#7]
I'm a rookie.whether I can access my own data？ what am I supposed to do?  , Thank you so much!!！

**Comment by rafaelklaessen** [comment]
Sorry, what do you mean with your own data?

**Comment by jiameng123** [comment]
sorry, How to set Local Data

**Comment by jiameng123** [comment]
How to connect my data and remove logo ?

**Comment by rafaelklaessen** [comment]
What are you trying to do? This is a wrapper around [this widget](https://www.tradingview.com/widget/advanced-chart/), that's all.

**Comment by jiameng123** [comment]
thanks !
