### ISSUE TITLE
Using custom charts

### ISSUE THREAD

**Issue by RodolfoQMartins** [rafaelklaessen/react-tradingview-widget#9]
I'm trying to use a custom chart from tradingview website, example:

```
 b.propTypes = {
            widgetType: u.a.string,
            width: u.a.number,
            height: u.a.number,
          	chart: u.a.string,
```
As a parameter:

```
 <TradingViewWidget
    symbol="NASDAQ:AAPL"
    theme="Dark"
    locale="en"
    chart="v6JkCe1X"

```
But it's seems it doesn't work, is there a way?

**Comment by rafaelklaessen** [comment]
Could you link me to the corresponding TradingView docs?

**Comment by RodolfoQMartins** [comment]
For example in the widget HTML5:

```
<script type="text/javascript">
var tradingview_embed_options = {};
tradingview_embed_options.width = '640';
tradingview_embed_options.height = '400';
tradingview_embed_options.chart = 'VsWWlqdP';
new TradingView.chart(tradingview_embed_options);
</script>
```

Parameter 'options.chart' its the custom layout that you gonna use.

**Comment by rafaelklaessen** [comment]
Have you tried setting the widgetType prop to `"chart"`?

**Comment by RodolfoQMartins** [comment]
@rafaelklaessen It Works! Thanks!!

**Comment by rafaelklaessen** [comment]
Great! :smile: I'll look at the documentation tomorrow

**Comment by mburakergenc** [comment]
> @rafaelklaessen It Works! Thanks!!

Hi,
Faced the same problem. Do you still have the snippet? :)
